export const constant = {
    URL_LOGIN: '/login',
    URL_CHECK_USER: '/check_user',
    URL_FETCH_ALL_USERS: '/fetch_all_users',
    URL_ADD_NEW_USER: '/add_new_user',
    URL_DELETE_USER: '/delete_user',
    URL_UPDATE_USER: '/update_user',

    URL_GET_ALL_ACTIVE_USERS: '/get_all_active_users',
    URL_GET_ALL_ROLES: '/get_all_roles',
    URL_GET_ALL_AGENTS: '/get_all_agents',

    PROJECTS_URL: 'getProjects',
    PROJECTS_NSP: '/project',
    PROJECTS_LISTEN: 'allProjects',
    PROJECTS_RESPONSE: 'projectResponse',
    PROJECTS_CREATE: 'createProject',
    PROJECTS_DELETE: 'deleteProject',
    PROJECTS_UPDATE: 'updateProject',
    PROJECTS_COPY: 'copyProject',

    DOMAINS_URL: 'getDomains',
    DOMAINS_NSP: '/domain',
    DOMAINS_LISTEN: 'allDomains',
    DOMAINS_RESPONSE: 'domainResponse',
    DOMAINS_CREATE: 'createDomain',
    DOMAINS_DELETE: 'deleteDomain',
    DOMAINS_UPDATE: 'updateDomain',

    IRS_NSP: '/dashboard',
    IRS_INTENTS_URL: 'getIntents',
    IRS_INTENTS_LISTEN: 'allIntents',
    IRS_INTENTS_RESPONSE: 'intentResponse',
    IRS_INTENTS_CREATE: 'createIntent',
    IRS_INTENTS_UPDATE: 'updateIntent',
    IRS_INTENTS_DELETE: 'deleteIntent',
    IRS_RESPONSES_URL: 'getResponses',
    IRS_RESPONSES_LISTEN: 'allResponses',
    IRS_RESPONSES_RESPONSE: 'respResponse',
    IRS_RESPONSES_CREATE: 'createResponse',
    IRS_RESPONSES_UPDATE: 'updateResponse',
    IRS_RESPONSES_DELETE: 'deleteResponse',
    IRS_STORIES_URL: 'getStories',
    IRS_STORIES_LISTEN: 'allStories',
    IRS_STORIES_RESPONSE: 'storyResponse',
    IRS_STORIES_CREATE: 'createStory',
    IRS_STORIES_UPDATE: 'updateStory',
    IRS_STORIES_DELETE: 'deleteStory',

    INTENT_NSP: '/intent',
    INTENT_DETAILS_URL: 'getIntentDetails',
    INTENT_DETAILS_LISTEN: 'intentDetail',
    INTENT_TEXT_CREATE: 'insertIntentDetails',
    INTENT_TEXT_UPDATE: 'updateIntentDetails',
    INTENT_TEXT_DELETE: 'deleteIntentDetails',

    RESPONSE_NSP: '/response',
    RESPONSE_DETAILS_URL: 'getResponseDetails',
    RESPONSE_DETAILS_LISTEN: 'responseDetail',
    RESPONSE_TEXT_CREATE: 'insertResponseDetails',
    RESPONSE_TEXT_DELETE: 'deleteResponseDetails',

    STORY_NSP: '/story',
    STORY_DETAILS_URL: 'getStoryDetails',
    STORY_ALERT_DETAILS_LISTEN: 'respStoryDetail',
    STORY_DETAILS_LISTEN: 'storyDetail',
    STORY_DETAILS_INSERT: 'insertStoryDetails',
    STORY_DETAILS_DELETE: 'deleteStoryDetails',
    STORY_DETAILS_UPDATE: 'updateStoryDetails',

    ENTITIES_NSP: '/nav',
    ENTITIES_URL: 'getEntities',
    ENTITIES_LISTEN: 'allEntities',
    ENTITIES_RESPONSE: 'entitiesResponse',
    ENTITIES_CREATE: 'createEntity',
    ENTITIES_UPDATE: 'updateEntity',
    ENTITIES_DELETE: 'deleteEntity',

    TRY_NOW_NSP: '/trynow',
    TRY_NOW_URL: 'tryNow',
    CHAT_NOW_URL: 'chatNow',
    TRY_NOW_LISTEN: 'chatResponse',

    PROJECT_DEPLOY_NSP: '/modelpublish',
    PROJECT_DEPLOY_URL: 'getDashboard',
    MODEL_DEPLOY_URL: 'trainModel',
    PROJECT_DEPLOY_LISTEN: 'respModelPublish',
    MODEL_DEPLOY_LISTEN: 'publishMessage',

    MODULE_COMMON: 'common',
    MODULE_MODEL: 'model',
};

